# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.30

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\Qt\Tools\CMake_64\bin\cmake.exe

# The command to remove a file.
RM = C:\Qt\Tools\CMake_64\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\pc\Desktop\2025-l2g1\trunk\L2G1_Module3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\pc\Desktop\2025-l2g1\trunk\L2G1_Module3\build\Desktop_Qt_6_11_0_MinGW_64_bit-Debug

# Include any dependencies generated for this target.
include CMakeFiles/L2G1_Module3.dir/depend.make
# Include any dependencies generated by the compiler for this target.
include CMakeFiles/L2G1_Module3.dir/compiler_depend.make

# Include the progress variables for this target.
include CMakeFiles/L2G1_Module3.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/L2G1_Module3.dir/flags.make

CMakeFiles/L2G1_Module3.dir/L2G1_Module3_autogen/mocs_compilation.cpp.obj: CMakeFiles/L2G1_Module3.dir/flags.make
CMakeFiles/L2G1_Module3.dir/L2G1_Module3_autogen/mocs_compilation.cpp.obj: CMakeFiles/L2G1_Module3.dir/includes_CXX.rsp
CMakeFiles/L2G1_Module3.dir/L2G1_Module3_autogen/mocs_compilation.cpp.obj: L2G1_Module3_autogen/mocs_compilation.cpp
CMakeFiles/L2G1_Module3.dir/L2G1_Module3_autogen/mocs_compilation.cpp.obj: CMakeFiles/L2G1_Module3.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=C:\Users\pc\Desktop\2025-l2g1\trunk\L2G1_Module3\build\Desktop_Qt_6_11_0_MinGW_64_bit-Debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object CMakeFiles/L2G1_Module3.dir/L2G1_Module3_autogen/mocs_compilation.cpp.obj"
	C:\Qt\Tools\mingw1310_64\bin\g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/L2G1_Module3.dir/L2G1_Module3_autogen/mocs_compilation.cpp.obj -MF CMakeFiles\L2G1_Module3.dir\L2G1_Module3_autogen\mocs_compilation.cpp.obj.d -o CMakeFiles\L2G1_Module3.dir\L2G1_Module3_autogen\mocs_compilation.cpp.obj -c C:\Users\pc\Desktop\2025-l2g1\trunk\L2G1_Module3\build\Desktop_Qt_6_11_0_MinGW_64_bit-Debug\L2G1_Module3_autogen\mocs_compilation.cpp

CMakeFiles/L2G1_Module3.dir/L2G1_Module3_autogen/mocs_compilation.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/L2G1_Module3.dir/L2G1_Module3_autogen/mocs_compilation.cpp.i"
	C:\Qt\Tools\mingw1310_64\bin\g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E C:\Users\pc\Desktop\2025-l2g1\trunk\L2G1_Module3\build\Desktop_Qt_6_11_0_MinGW_64_bit-Debug\L2G1_Module3_autogen\mocs_compilation.cpp > CMakeFiles\L2G1_Module3.dir\L2G1_Module3_autogen\mocs_compilation.cpp.i

CMakeFiles/L2G1_Module3.dir/L2G1_Module3_autogen/mocs_compilation.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/L2G1_Module3.dir/L2G1_Module3_autogen/mocs_compilation.cpp.s"
	C:\Qt\Tools\mingw1310_64\bin\g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S C:\Users\pc\Desktop\2025-l2g1\trunk\L2G1_Module3\build\Desktop_Qt_6_11_0_MinGW_64_bit-Debug\L2G1_Module3_autogen\mocs_compilation.cpp -o CMakeFiles\L2G1_Module3.dir\L2G1_Module3_autogen\mocs_compilation.cpp.s

CMakeFiles/L2G1_Module3.dir/main.cpp.obj: CMakeFiles/L2G1_Module3.dir/flags.make
CMakeFiles/L2G1_Module3.dir/main.cpp.obj: CMakeFiles/L2G1_Module3.dir/includes_CXX.rsp
CMakeFiles/L2G1_Module3.dir/main.cpp.obj: C:/Users/pc/Desktop/2025-l2g1/trunk/L2G1_Module3/main.cpp
CMakeFiles/L2G1_Module3.dir/main.cpp.obj: CMakeFiles/L2G1_Module3.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=C:\Users\pc\Desktop\2025-l2g1\trunk\L2G1_Module3\build\Desktop_Qt_6_11_0_MinGW_64_bit-Debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building CXX object CMakeFiles/L2G1_Module3.dir/main.cpp.obj"
	C:\Qt\Tools\mingw1310_64\bin\g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/L2G1_Module3.dir/main.cpp.obj -MF CMakeFiles\L2G1_Module3.dir\main.cpp.obj.d -o CMakeFiles\L2G1_Module3.dir\main.cpp.obj -c C:\Users\pc\Desktop\2025-l2g1\trunk\L2G1_Module3\main.cpp

CMakeFiles/L2G1_Module3.dir/main.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/L2G1_Module3.dir/main.cpp.i"
	C:\Qt\Tools\mingw1310_64\bin\g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E C:\Users\pc\Desktop\2025-l2g1\trunk\L2G1_Module3\main.cpp > CMakeFiles\L2G1_Module3.dir\main.cpp.i

CMakeFiles/L2G1_Module3.dir/main.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/L2G1_Module3.dir/main.cpp.s"
	C:\Qt\Tools\mingw1310_64\bin\g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S C:\Users\pc\Desktop\2025-l2g1\trunk\L2G1_Module3\main.cpp -o CMakeFiles\L2G1_Module3.dir\main.cpp.s

CMakeFiles/L2G1_Module3.dir/mainwindow.cpp.obj: CMakeFiles/L2G1_Module3.dir/flags.make
CMakeFiles/L2G1_Module3.dir/mainwindow.cpp.obj: CMakeFiles/L2G1_Module3.dir/includes_CXX.rsp
CMakeFiles/L2G1_Module3.dir/mainwindow.cpp.obj: C:/Users/pc/Desktop/2025-l2g1/trunk/L2G1_Module3/mainwindow.cpp
CMakeFiles/L2G1_Module3.dir/mainwindow.cpp.obj: CMakeFiles/L2G1_Module3.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=C:\Users\pc\Desktop\2025-l2g1\trunk\L2G1_Module3\build\Desktop_Qt_6_11_0_MinGW_64_bit-Debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building CXX object CMakeFiles/L2G1_Module3.dir/mainwindow.cpp.obj"
	C:\Qt\Tools\mingw1310_64\bin\g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/L2G1_Module3.dir/mainwindow.cpp.obj -MF CMakeFiles\L2G1_Module3.dir\mainwindow.cpp.obj.d -o CMakeFiles\L2G1_Module3.dir\mainwindow.cpp.obj -c C:\Users\pc\Desktop\2025-l2g1\trunk\L2G1_Module3\mainwindow.cpp

CMakeFiles/L2G1_Module3.dir/mainwindow.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/L2G1_Module3.dir/mainwindow.cpp.i"
	C:\Qt\Tools\mingw1310_64\bin\g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E C:\Users\pc\Desktop\2025-l2g1\trunk\L2G1_Module3\mainwindow.cpp > CMakeFiles\L2G1_Module3.dir\mainwindow.cpp.i

CMakeFiles/L2G1_Module3.dir/mainwindow.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/L2G1_Module3.dir/mainwindow.cpp.s"
	C:\Qt\Tools\mingw1310_64\bin\g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S C:\Users\pc\Desktop\2025-l2g1\trunk\L2G1_Module3\mainwindow.cpp -o CMakeFiles\L2G1_Module3.dir\mainwindow.cpp.s

# Object files for target L2G1_Module3
L2G1_Module3_OBJECTS = \
"CMakeFiles/L2G1_Module3.dir/L2G1_Module3_autogen/mocs_compilation.cpp.obj" \
"CMakeFiles/L2G1_Module3.dir/main.cpp.obj" \
"CMakeFiles/L2G1_Module3.dir/mainwindow.cpp.obj"

# External object files for target L2G1_Module3
L2G1_Module3_EXTERNAL_OBJECTS =

L2G1_Module3.exe: CMakeFiles/L2G1_Module3.dir/L2G1_Module3_autogen/mocs_compilation.cpp.obj
L2G1_Module3.exe: CMakeFiles/L2G1_Module3.dir/main.cpp.obj
L2G1_Module3.exe: CMakeFiles/L2G1_Module3.dir/mainwindow.cpp.obj
L2G1_Module3.exe: CMakeFiles/L2G1_Module3.dir/build.make
L2G1_Module3.exe: C:/Qt/6.11.0/mingw_64/lib/libQt6Widgets.a
L2G1_Module3.exe: C:/Qt/6.11.0/mingw_64/lib/libQt6Gui.a
L2G1_Module3.exe: C:/Qt/6.11.0/mingw_64/lib/libQt6Core.a
L2G1_Module3.exe: C:/Qt/6.11.0/mingw_64/lib/libQt6EntryPoint.a
L2G1_Module3.exe: CMakeFiles/L2G1_Module3.dir/linkLibs.rsp
L2G1_Module3.exe: CMakeFiles/L2G1_Module3.dir/objects1.rsp
L2G1_Module3.exe: CMakeFiles/L2G1_Module3.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --bold --progress-dir=C:\Users\pc\Desktop\2025-l2g1\trunk\L2G1_Module3\build\Desktop_Qt_6_11_0_MinGW_64_bit-Debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Linking CXX executable L2G1_Module3.exe"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles\L2G1_Module3.dir\link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/L2G1_Module3.dir/build: L2G1_Module3.exe
.PHONY : CMakeFiles/L2G1_Module3.dir/build

CMakeFiles/L2G1_Module3.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles\L2G1_Module3.dir\cmake_clean.cmake
.PHONY : CMakeFiles/L2G1_Module3.dir/clean

CMakeFiles/L2G1_Module3.dir/depend:
	$(CMAKE_COMMAND) -E cmake_depends "MinGW Makefiles" C:\Users\pc\Desktop\2025-l2g1\trunk\L2G1_Module3 C:\Users\pc\Desktop\2025-l2g1\trunk\L2G1_Module3 C:\Users\pc\Desktop\2025-l2g1\trunk\L2G1_Module3\build\Desktop_Qt_6_11_0_MinGW_64_bit-Debug C:\Users\pc\Desktop\2025-l2g1\trunk\L2G1_Module3\build\Desktop_Qt_6_11_0_MinGW_64_bit-Debug C:\Users\pc\Desktop\2025-l2g1\trunk\L2G1_Module3\build\Desktop_Qt_6_11_0_MinGW_64_bit-Debug\CMakeFiles\L2G1_Module3.dir\DependInfo.cmake "--color=$(COLOR)"
.PHONY : CMakeFiles/L2G1_Module3.dir/depend

